const { Gateway, Wallets } = require('fabric-network');
const path = require('path');
const fs = require('fs');

const CHANNEL_NAME = 'mychannel';
const CHAINCODE_NAME = 'basic'; // Using the standard 'basic' name from samples
const MSP_ID = 'Org1MSP';
const USER_ID = 'appUser'; // We will register this user in the wallet

async function connectToNetwork() {
    // Path to common connection profile (will be generated by test-network)
    const ccpPath = path.resolve(__dirname, '..', '..', 'locket-network', 'fabric-samples', 'test-network', 'organizations', 'peerOrganizations', 'org1.example.com', 'connection-org1.json');
    
    // Check if CCP exists (it won't until network is up)
    if (!fs.existsSync(ccpPath)) {
        throw new Error(`Connection profile not found at ${ccpPath}. Is the Fabric network running?`);
    }

    const ccp = JSON.parse(fs.readFileSync(ccpPath, 'utf8'));

    // Setup Wallet
    const walletPath = path.join(process.cwd(), 'wallet');
    const wallet = await Wallets.newFileSystemWallet(walletPath);
    
    // Check if user exists
    const identity = await wallet.get(USER_ID);
    if (!identity) {
        throw new Error(`Identity "${USER_ID}" not found in wallet. Run the enrollment script first.`);
    }

    const gateway = new Gateway();
    await gateway.connect(ccp, {
        wallet,
        identity: USER_ID,
        discovery: { enabled: true, asLocalhost: true }
    });

    const network = await gateway.getNetwork(CHANNEL_NAME);
    const contract = network.getContract(CHAINCODE_NAME);

    return { gateway, contract };
}

async function submitTransaction(functionName, ...args) {
    const { gateway, contract } = await connectToNetwork();
    try {
        console.log(`[Fabric] Submitting: ${functionName}(${args.join(', ')})`);
        const result = await contract.submitTransaction(functionName, ...args);
        console.log('[Fabric] Transaction committed');
        return { transactionId: 'unknown-for-now', result: result.toString() };
    } finally {
        gateway.disconnect();
    }
}

async function evaluateTransaction(functionName, ...args) {
    const { gateway, contract } = await connectToNetwork();
    try {
        console.log(`[Fabric] Evaluating: ${functionName}(${args.join(', ')})`);
        const result = await contract.evaluateTransaction(functionName, ...args);
        return result.toString();
    } finally {
        gateway.disconnect();
    }
}

module.exports = {
    connectToNetwork,
    submitTransaction,
    evaluateTransaction
};
