#!/usr/bin/env bash
# validate-fabric-env.sh — Pre-flight check for Hyperledger Fabric test-network crypto material.
# Exits non-zero with a clear error message if anything required is missing.
# Run this before starting the serverless-gateway dev server.
#
# Usage:
#   ./network/validate-fabric-env.sh
#   ./network/validate-fabric-env.sh --fix   # also runs start-network.sh if crypto missing
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FABRIC_SAMPLES="${SCRIPT_DIR}/fabric-samples"
TEST_NETWORK="${FABRIC_SAMPLES}/test-network"
ORG1_PATH="${TEST_NETWORK}/organizations/peerOrganizations/org1.example.com"

RED='\033[0;31m'
YLW='\033[0;33m'
GRN='\033[0;32m'
BLD='\033[1m'
RST='\033[0m'

fail() {
    echo -e "${RED}${BLD}[fabric-env] FAIL:${RST} $*" >&2
    exit 1
}

warn() {
    echo -e "${YLW}[fabric-env] WARN:${RST} $*" >&2
}

ok() {
    echo -e "${GRN}[fabric-env]  OK :${RST} $*"
}

# ── 1. fabric-samples clone ───────────────────────────────────────────────────
[[ -d "${FABRIC_SAMPLES}" ]] \
    || fail "fabric-samples directory not found at '${FABRIC_SAMPLES}'.
  Fix: ensure the repo is cloned or the git submodule is initialised:
    git submodule update --init --recursive
  or run: ./network/install-fabric.sh samples"

[[ -d "${TEST_NETWORK}" ]] \
    || fail "test-network directory not found inside fabric-samples ('${TEST_NETWORK}').
  The fabric-samples clone looks incomplete. Re-clone or re-init:
    rm -rf '${FABRIC_SAMPLES}' && ./network/install-fabric.sh samples"

ok "fabric-samples/test-network present"

# ── 2. network.sh executable ─────────────────────────────────────────────────
[[ -x "${TEST_NETWORK}/network.sh" ]] \
    || fail "'${TEST_NETWORK}/network.sh' not found or not executable.
  Fix: cd '${FABRIC_SAMPLES}' && git checkout main"

ok "test-network/network.sh executable"

# ── 3. Crypto material (generated by ./network.sh up) ────────────────────────
REQUIRED_FILES=(
    "${ORG1_PATH}/peers/peer0.org1.example.com/tls/ca.crt"
    "${ORG1_PATH}/ca/ca.org1.example.com-cert.pem"
)

# Dirs that must exist and be non-empty (filename varies by enrollment method)
REQUIRED_DIRS=(
    "${ORG1_PATH}/users/User1@org1.example.com/msp/keystore"
    "${ORG1_PATH}/users/User1@org1.example.com/msp/signcerts"
)

missing=0

for f in "${REQUIRED_FILES[@]}"; do
    if [[ -f "${f}" ]]; then
        ok "$(basename "${f}")"
    else
        warn "Missing file: ${f}"
        missing=$((missing + 1))
    fi
done

for d in "${REQUIRED_DIRS[@]}"; do
    if [[ -d "${d}" ]] && [[ -n "$(ls -A "${d}" 2>/dev/null)" ]]; then
        ok "$(basename "${d}") dir populated ($(ls "${d}" | wc -l | tr -d ' ') file(s))"
    else
        warn "Missing or empty directory: ${d}"
        missing=$((missing + 1))
    fi
done

if [[ "${missing}" -gt 0 ]]; then
    echo >&2
    echo -e "${RED}${BLD}[fabric-env] ${missing} required crypto file(s)/dir(s) are missing.${RST}" >&2
    echo -e "${YLW}  These are generated by the test-network. To create them:${RST}" >&2
    echo -e "    cd '${SCRIPT_DIR}'" >&2
    echo -e "    ./start-network.sh" >&2
    echo >&2
    echo -e "  If you want to skip Fabric (mock mode), set the environment variable:" >&2
    echo -e "    export FABRIC_MOCK=true" >&2
    echo >&2

    if [[ "${1:-}" == "--fix" ]]; then
        echo -e "${YLW}[fabric-env] --fix passed: running start-network.sh now...${RST}" >&2
        cd "${SCRIPT_DIR}"
        bash start-network.sh
    else
        fail "Crypto material incomplete. Run with --fix to auto-start the network, or see above."
    fi
fi

# ── 4. Fabric binaries in PATH (informational) ────────────────────────────────
BINS_PATH="${FABRIC_SAMPLES}/bin"
if [[ -d "${BINS_PATH}" ]]; then
    ok "Fabric binaries present at ${BINS_PATH}"
    if ! echo "${PATH}" | grep -q "${BINS_PATH}"; then
        warn "Fabric bin dir not in PATH. Add it:  export PATH=\"${BINS_PATH}:\${PATH}\""
    fi
else
    warn "Fabric binaries not found at '${BINS_PATH}'. Gateway will use Docker peer CLI. Run:
    ./network/install-fabric.sh binary"
fi

# ── 5. Docker availability ────────────────────────────────────────────────────
if command -v docker &>/dev/null && docker info &>/dev/null 2>&1; then
    ok "Docker running"
else
    warn "Docker is not running or not installed. The test-network requires Docker."
fi

echo
echo -e "${GRN}${BLD}[fabric-env] Pre-flight checks passed. Safe to start the gateway.${RST}"
